// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza.API.Data;

#nullable disable

namespace Pizza.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240212171629_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IngredientModelPizzaModel", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("PizzasId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "PizzasId");

                    b.HasIndex("PizzasId");

                    b.ToTable("IngredientModelPizzaModel");
                });

            modelBuilder.Entity("Pizza.API.Models.IngredientModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nom");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Prix");

                    b.HasKey("Id");

                    b.ToTable("Ingrédient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tomates fraîches",
                            Name = "Tomate",
                            Price = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mozzarella fondante",
                            Name = "Fromage",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pepperoni épicé",
                            Name = "Pepperoni",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jambon de qualité supérieure",
                            Name = "Jambon",
                            Price = 2.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Champignons frais",
                            Name = "Champignons",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Olives noires",
                            Name = "Olives",
                            Price = 1.00m
                        });
                });

            modelBuilder.Entity("Pizza.API.Models.PizzaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Categorie")
                        .HasColumnType("int")
                        .HasColumnName("Categorie");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nom");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Prix");

                    b.HasKey("Id");

                    b.ToTable("Pizza");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = 0,
                            Description = "Simple et classique.",
                            Nom = "Margherita",
                            Prix = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            Categorie = 2,
                            Description = "Piquante avec pepperoni.",
                            Nom = "Pepperoni",
                            Prix = 12.00m
                        },
                        new
                        {
                            Id = 3,
                            Categorie = 0,
                            Description = "Riche en fromages.",
                            Nom = "Quatre fromages",
                            Prix = 13.00m
                        },
                        new
                        {
                            Id = 4,
                            Categorie = 1,
                            Description = "Garnie de légumes frais.",
                            Nom = "Végétarienne",
                            Prix = 11.00m
                        },
                        new
                        {
                            Id = 5,
                            Categorie = 0,
                            Description = "Jambon et ananas.",
                            Nom = "Hawaïenne",
                            Prix = 12.00m
                        },
                        new
                        {
                            Id = 6,
                            Categorie = 3,
                            Description = "Pliée et farcie, garnie de jambon, champignons et fromage.",
                            Nom = "Calzone",
                            Prix = 14.00m
                        });
                });

            modelBuilder.Entity("Pizza.API.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresse postale");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date de naissance");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prénom");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("Administrateur");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nom de famille");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mot de passe");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Numéro de téléphone");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown",
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IsAdmin = false,
                            LastName = "Doe",
                            Password = "Password1",
                            PhoneNumber = "0123456789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Another St, Anytown",
                            DateOfBirth = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            LastName = "Doe",
                            Password = "Password2",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Admin St, Anytown",
                            DateOfBirth = new DateTime(1985, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@example.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "User",
                            Password = "AdminPassword",
                            PhoneNumber = "1234567890"
                        });
                });

            modelBuilder.Entity("IngredientModelPizzaModel", b =>
                {
                    b.HasOne("Pizza.API.Models.IngredientModel", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pizza.API.Models.PizzaModel", null)
                        .WithMany()
                        .HasForeignKey("PizzasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
